enableDashboardAccess: true
enableWebAccess: true

workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-8
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/aa-ai-specialisation/bf-repo/bfd

baseOutputDirectory:
  outputUriPrefix: gs://specialization_black_friday